name: Tests on push
on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ feature/** ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - run: npm ci
    - name: Run tests
      run: npm run test:prod
    - name: Lint
      run: npm run lint